-- auto Generated on 2020-03-05
-- DROP TABLE IF EXISTS shop;
CREATE TABLE shop(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	admin_id INT (11) NOT NULL DEFAULT -1 COMMENT 'adminId',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'shop';
