server:
  port: 8088
  servlet:
    context-path: /jpa
spring:
  datasource:
    url: jdbc:mysql://106.13.79.230:3306/springboot?useUnicode=truecharacterEncoding=UTF-8
    username: fushuai
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    host: 106.13.79.230
    #服务器地址
    port: 6379
    #服务器端口
    database: 0
    # Redis数据库索引（默认为0） 密码之类的 默认是没有的可以写
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
