server:
  port: 8081
  servlet:
      context-path: /app

spring:
  datasource:
    url: jdbc:mysql://106.13.79.230:3306/springboot?useUnicode=truecharacterEncoding=UTF-8
    username: fushuai
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#复杂对象形式的配置项

fuza:
  welcome: 欢迎
  img: 1.png

