spring:
  datasource:
    url: jdbc:mysql://106.13.79.230:3306/mobileapp?useUnicode=truecharacterEncoding=UTF-8
    username: fushuai
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.example.demo: info
  file:
    name: myLog.log
